name: vote-app-pipeline
on: push
env:
    serviceName: vote
    depName: voting-app-deployment
    containerName: voting-app-container
    environment: green
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3   # important to checkout code
      - name: fetching short commit id
        run: |
             commitId=$(echo ${{ github.sha }})
             shortCommitId=${commitId:0:7}
             echo "SHORT_COMMIT_ID=$shortCommitId" >> $GITHUB_ENV

      - name: ACR login
        uses: docker/login-action@v3
        with:
            registry: ${{secrets.ACR_LOGIN_SERVER}}
            username: ${{secrets.ACR_USER_NAME}}
            password: ${{secrets.ACR_PASSWORD}}

      - name: image build
        run: |
             echo "comm id: $shortCommitId" ;docker build  -t ${{secrets.ACR_LOGIN_SERVER}}/$serviceName:$SHORT_COMMIT_ID . 

      - name: Set full image tag
        run: |
          IMAGE_TAG="${{ secrets.ACR_LOGIN_SERVER }}/$serviceName:$SHORT_COMMIT_ID"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE_TAG }}
          format: 'table'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '1'

      - name: image push to ACR.
        run: docker push ${{secrets.ACR_LOGIN_SERVER}}/$serviceName:$SHORT_COMMIT_ID

      - name: Load kubeconfig
        env:
            KUBE_CONFIG_DATA: ${{secrets.KUBE_CONFIG_DATA}}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG_DATA"
          echo "$KUBE_CONFIG_DATA"|base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          
      - name: updating image
        run: |
             kubectl set image deployment/$depName $containerName=${{secrets.ACR_LOGIN_SERVER}}/$serviceName:$SHORT_COMMIT_ID -n $environment
             kubectl rollout status deployment/$depName --timeout=120s -n $environment
             if [ $? -ne 0 ];then
                echo "Deployment failed!,Rollback happening for $depName "
                kuebctl rollout undo deployment/$depName -n $environment
             else
                echo "Deployment successfull"

             fi
            


